// ─── Mainchat core contracts ────────────────────────────────────────────────
// Every connector, the vibe engine, and the UI build against these types.

export type PlatformId = "twitch" | "kick" | "x";

export type Badge = "owner" | "mod" | "vip" | "sub" | "og" | "verified";

export type VibeTag = "bet" | "hype" | "question";

export interface VibeInfo {
  /** -3..+3 sentiment score for this single message */
  score: number;
  tags: VibeTag[];
  toxic: boolean;
}

export interface ChatMessage {
  id: string;
  platform: PlatformId;
  /** login / handle, lowercase, no @ */
  username: string;
  displayName: string;
  text: string;
  /** user-chosen chat color if the platform provides one (hex) */
  color?: string;
  badges: Badge[];
  /** epoch ms */
  timestamp: number;
  /** true when generated by the demo feed */
  isDemo?: boolean;
  avatarUrl?: string;
  vibe: VibeInfo;
}

export type ConnState =
  | "idle"
  | "connecting"
  | "connected"
  | "reconnecting"
  | "error"
  | "unconfigured"
  | "disabled";

export interface PlatformStatus {
  state: ConnState;
  /** short human-readable detail, e.g. "joined #fazebanks" or an error hint */
  detail?: string;
  live?: boolean;
  viewers?: number | null;
  streamTitle?: string;
}

export interface ConnectorEvents {
  onMessage: (msg: ChatMessage) => void;
  onStatus: (status: PlatformStatus) => void;
}

/** Every chat source implements this. start() must be safe to call once;
 *  stop() must tear down sockets/timers and silence all callbacks. */
export interface Connector {
  start(): void;
  stop(): void;
}

// ─── App configuration ──────────────────────────────────────────────────────

export interface AppConfig {
  twitchChannel: string;
  kickChannel: string;
  /** X search query (recent search syntax) */
  xQuery: string;
  enabled: Record<PlatformId, boolean>;
  demoMode: boolean;
  brandPreset: "marketbubble" | "custom";
  brandName: string;
  toxicityFilter: boolean;
}

// ─── Vibe engine aggregate output ───────────────────────────────────────────

export interface TopChatter {
  username: string;
  displayName: string;
  platform: PlatformId;
  count: number;
}

export interface VibeSnapshot {
  /** 0..100 rolling crowd-sentiment meter */
  meter: number;
  /** e.g. "euphoric" | "cooking" | "steady" | "shaky" | "rugging" */
  label: string;
  topChatters: TopChatter[];
  /** trending keywords, most frequent first */
  keywords: string[];
  /** bet-flavored messages seen in the window */
  betCount: number;
  /** messages per minute across all platforms */
  rate: number;
}
